language: java
sudo: false
install: true
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

services:
  - docker

env:
  global:
  - ACCESS_KEY=2HKPQS0L01432IOCEEBI
  - SECRET_KEY=xyaf2ol7RCMZPoNFxWDjQyyX2qq6X8SF8cAEs0FP
  - S3_HOST="http://localhost:9000"

before_install:
  - docker run -d -p 9000:9000 -e "MINIO_ACCESS_KEY=${ACCESS_KEY}" -e "MINIO_SECRET_KEY=${SECRET_KEY}" minio/minio server /data